### ISSUE TITLE
dropdown on search field not always visible

### ISSUE THREAD

**Issue by jorian** [pbca26/insight-ui-komodo#1] opened 2020-01-18 18:37 UTC
OS: macOs 10.14.6
Browser: Firefox

This concerns the explorer that is hosted at https://explorer.komodoplatform.com 
If I want to use the multi-asset explorer, I have to make the browser window smaller (i assume the cutoff for making the screen responsive):

<img width="755" alt="image" src="https://user-images.githubusercontent.com/10341677/72668596-ccf60700-3a28-11ea-860e-f40ee72a4f88.png">

There is no dropdown next to the search field. Now if I make the window smaller:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/10341677/72668605-00389600-3a29-11ea-9663-22c837190376.png">

I can select the `All coins` option.

I started messing with things a bit in the inspector and noticed that on the search bar element, if i change the width calculator (changed `300 - 30` to `300 - 300`):
<img width="353" alt="image" src="https://user-images.githubusercontent.com/10341677/72668678-ad131300-3a29-11ea-810a-48322959d582.png">
the dropdown appears:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/10341677/72668687-bb612f00-3a29-11ea-946a-5f5fb519817c.png">

**Comment by TheComputerGenie** [comment] 2020-01-19 13:53
Can confirm changing 300 - 30 to 300 - 300 works with 1920x1080 fire/waterfox

**Comment by pbca26** [comment] 2020-02-13 13:19
@jorian the issue is fixed. Can you try it please?

**Comment by jorian** [comment] 2020-02-20 18:18
@pbca26 it has been fixed!

**Comment by pbca26** [comment] 2020-02-20 19:02
great, closing the issue

**Closed by pbca26** 2020-02-20 19:02 UTC
